name: Deploy PHP Project with Backup

on:
  push:
    branches:
      - deploy  # Trigger deployment when changes are pushed to the 'deploy' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (custom script for the checkout)
      - name: Checkout repository
        run: |
          git clone https://github.com/${{ github.repository }} .
      
      # Step 2: Set up PHP manually
      - name: Set up PHP 8.1
        run: |
          sudo apt update
          sudo apt install php8.1 php8.1-cli php8.1-fpm php8.1-mysql php8.1-xml php8.1-mbstring php8.1-curl php8.1-zip -y

      # Step 3: Install PHP dependencies
      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      # Step 4: Backup current repository files (to repository, not server)
      - name: Create Backup in Repository
        run: |
          BACKUP_DIR=$(mktemp -d)  # Create a temporary directory
          
          # Use rsync to copy all files except excluded ones
          rsync -av --exclude='.git' --exclude='vendor/' --exclude='node_modules/' --exclude='backup/' ./ "$BACKUP_DIR/"

          # Create the backup directory if it doesn't exist
          mkdir -p backup
          
          # Archive the backup into the `backup` folder
          tar -czvf backup/backup.tar.gz -C "$BACKUP_DIR" .

          # Clean up temporary directory
          rm -rf "$BACKUP_DIR"

      # Step 5: Commit the backup to the repository
      - name: Commit Backup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add backup/
          git commit -m "Backup before deployment"
          git push

      # Step 6: Deploy to FTP Server (overwrite if necessary)
      - name: Deploy to FTP server using custom script
        run: |
          ftp -n ${{ secrets.FTP_SERVER }} <<END_SCRIPT
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          binary
          cd /path/to/your/server/directory
          mput *
          quit
          END_SCRIPT
